[workspace]
members = ["tools/bindgen", "tools/clang"]
# members = ["tools/llvm"]

[workspace.package]
name = "qnarre"
license = "https://github.com/quantapix/qnarre"
version = "0.1.0"
edition = "2021"
