[package]
name = "qnarre"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# links = "llvm-16"

[dependencies]
docopt = "*"
serde = "*"
libc = "0.2"
llvm = { path = "./lib/llvm.rs" }
llvm-safe = { path = "./lib/llvm-safe.rs" }
# clang-sys = { version = "1.2.2", optional = true }
# tempfile = { version = "3.2.0", optional = true }

[build-dependencies]
cmake = "*"
cc = "1.0"
lazy_static = "1.0"
regex = "1"
semver = "1.0.7"
