[package]
name = "llvm"
version.workspace = true
edition.workspace = true
build = "build.rs"
# links = "llvm"

[build-dependencies]
bindgen = "0.65.1"

[dependencies]
criterion = "0.4.0"
macros = { path = "./macros" }
once_cell = "1"

[dev-dependencies]
indoc = "2.0.1"
insta = "1.29.0"
pretty_assertions = "1.3.0"

[[bench]]
name = "main"
harness = false
