#+title: Qnarre

* Introduction

The motivation behind the **qnarre** effort is our unconditional love for our children.

**Quantapix**, the software startup, was born as a precursor to the vicious, cruel and simply unimaginable, yet intuitively well-understood power struggle between the "elite" and the rest of us.

[Just as documented](https://femfas.net), advanced "weaponized psychology" has been used extensively by some "trusted" professionals of our most respected institutions. These elite predators knowingly hurt and tortured our children, while holding us ideological hostages for perhaps millions of dollars.

We believe, and with the following series of blogs, we attempt to publicly prove, that AI, or the more humble **"deep learning"** technology, is not all evil nor needs to be exclusively exploitative.

Despite the naive, uninformed and irrational fears of the inexperienced, "the enemy is within" in all tyrannies (e.g. fascism, communism, etc.) in the form of yet uncommunicated contradictions and intrinsic inconsistencies.

Our dream, along with our concrete, informed steps we continue to take to approach it, is to devise AI software to actively protect our **American-born children** from greedy professional torturing and forceful, institutionalized separation and isolation. Family Court-mandated, and even directly ordered, parental alienation, while paying astronomical profits to the "trusted" elite, is nothing but ruthless and cruel child abuse.

Seeking out **contradictions** and **inconsistencies** in "vast oceans" of deceitful data with ever-adapting, fluidly learning, yet still reproducible software mechanisms is exactly what AI, "the child protector" kind, was inherently invented for. It can rightfully become our openly shared ethical and moral reference, an always true, falsifiable and verifiably correctable guiding compass.

The following blogs incorporate "runnable" [Python](https://www.python.org/) scripts organized as [Jupyter](https://jupyter.org/) notebooks. Introduction to using these and other amazingly productive, state-of-the-art tools is well beyond our limited scope here. 


* Advanced TensorFlow 2.0 w/ Keras

** Introduction

Google's open-sourced TensorFlow, a top project on the "~36 million developers" GitHub, is arguably one of the most successful applications of the mathematics we understand and have come to personally love.

This amazingly capable, perhaps community developed tool suddenly allows us to study, and to also efficiently simulate, our insights and understanding of the fluid reality around us.

The new, cleaned-up version, the beta of TensorFlow 2.0, has just been released with its APIs now frozen. Personally motivated and eagerly curious to "read the sources", the following blogs document our process of learning and adjusting to TensorFlow 2.0.

/Note: the runnable examples currently depend on the "nightly" builds of TensorFlow 2.0 (downloadable with `!pip install -U tf-nightly-2.0-preview` from running Jupyter notebooks)./

** Trackable: A Pervasive Persistence Infrastructure

- Auto-tracking natively referenced modeling variables
- "Pythonic" aggregating and encapsulating in models
- Mixing new `modules` and Keras `layers` for seamless persistence
- "A picture is worth a thousand words": graphs with TensorBoard

Training in TensorFlow means continually adjusting collections of values stored as `tensors` in objects called `variables`.

The persistence of these variables, from one training session to the next, is critical for improving on the already achieved, but otherwise long-running results.

A new system-wide pervasive `trackable` architecture now provides just such a persistence infrastructure. Instead of the old name-based hierarchy, the new design applies a topological, "layered objects" naming scheme.

In this first blog, we explore some of the key aspects of this architecture. We start with a high-level view and then we gradually build from the simple base classes to the more useful Keras `layers`.

Our objective is to arrive at a training model representable by the [graph](./trackable.pdf).

We first need to prep our environment to run any meaningful code:

# code

The actual persistence of training data, the weights, is ultimately realized through explicit Checkpoint objects.

As the number of such representations grows, saved as efficiently encoded versioned files, CheckpointManagers help with keeping track (see TF docs for full functionality).

We present a simple scenario for persisting (saving and restoring) a single-valued variable encapsulated by a Trackable object as follows:

# code

Using the above function, our 3 iterations of incrementing the single-valued `int` variable and keeping track of the `Checkpoint` files result in:

# code

While the above snippet is fully functional, the extensive boiler-plate code becomes an unnecessary hassle when implementing even slightly more complex schemes.

Also note that we used a private, undocumented and non-API method to make our code work. A more convenient "auto-tracking" functionality is needed.

The native Python attribute mechanism conveniently provides a framework to satisfy such needs as we'll see in a moment.

In preparation, our slightly adjusted printing function is now as follows:

# code

And here is our use of an AutoTrackable object holding onto 2 single-valued variables.

Notice the intuitive tr2.v = tracked assignment, as this is where the entire "trackable" scheme is triggered.

Just in case we want to avoid the default functionality, we can turn off auto-tracking as well:

# code

Employing the native Python attribute mechanism and assignment operator allows us to reliably "auto track" hundreds or thousands of training variables.

Moreover, a consistent hierarchical "layered objects" naming scheme emerges, without the need for explicit, string-based names.

For a snapshot view of the "topology" of our layers, or just a simple inventory of our variables, we can use the helper functions provided by TF:

# code

Looking at the result of calling our function, we can quickly grasp the otherwise simple pattern of hierarchical naming convention employed by the architecture:

# code

Any type of variable management system that allows creating variables must also support deleting them.

The familiar native Python attribute mechanism's `del` operation is used to delete a variable from the hierarchy, just as shown below:

# code

And here are the results of calling our `deleting` function:

# code

Variable management also means possibly aggregating variables into various containers.

Intuitive Python list and dict structures can be transparently employed through the trackable mechanism.

Using our below-modified function to print our variables in our `containers':

# code

Just as mentioned above, we can intuitively collect variables into either lists or dicts.

And the patterns used for naming the thus aggregated variables are just as expected:

# code

Neural networks rely on sharing persisted trainable weights, TF variables in our case, to express interdependencies.

Variable sharing was ad-hoc, only name-based and with a global scope before.

As Python has extensive native support for managing easily sharable references to its objects, this fundamental problem gets an intuitive solution with the new trackable architecture.

As expected, sharing variables now is natural and also safe, as it uses references instead of error-prone strings:

# code

Persisted shared variables are not duplicated in checkpoints. And when checkpoints are restored or reloaded, the in-memory sharing of variables is also re-established.

Updates to our shared variables can be easily verified just as follows:

# code

Variable management also means possible encapsulation.

The new Module objects build on AutoTrackable to extend Python's familiar class-based encapsulation mechanism.

The also supported explicit name scoping of modules allows the reuse of module classes, as instances of the same class would need to be generically counted otherwise:

# code

When building hierarchies of modules, TF provided convenience methods also allow for recursively collecting the "layered" variables. This is essential for computing gradients:

# code

With our module class and our handy printing function, we can now build a basic nested hierarchy of 3 layered modules.

Printing our "one branch tree" shows both the name-based hierarchy and the Python-object or topological "checkpoint" hierarchy:

# code

Keras is the API for consistently reasoning about the interconnected network of components. It also visibly splits the two distinct, building vs. executing, phases of our component "graphs".

The `functional` Keras, as opposed to either the `sequential` or the `subclassed` flavors, has the most pre-packaged features to assist us with our neural networks. We aim to use it throughout our blogs.

Keras `layer`s, as well-defined encapsulating components, build on the previously used `module`s to manage variable persistence.

Hence, the previous `module`s example is almost identical to the below shown "Keras layers" version:

# code

And after adjusting our helper to print the results:

# code

We finally arrive at the most simple Keras model.

It uses just 3 scalar variables to showcase the underlying already tried and used persistence management:

# code

Nevertheless, even the simplest model can be overwhelming when expressed only textually.

TensorBoard is an accompanying tool that can help us in "picturing" the nested component graphs.

As "a picture is worth a thousand words", summary data for TB is generated as follows:

# code

Please note that our trivially simple Keras model still implements data-driven Python recursion.

The new autograph functionality allows us to use such intuitive, native expressions instead of the usual, but more cumbersome, TF "graph ops".

Autograph code generation is invoked with the tf.function Python decorator. A later blog will highlight the most impressive features of this new approach to defining ops.

# code

In order to see the TB generated summaries, including the picture of our graph, we need to load the extension:

# code

Then we generate the TB summaries by calling our tracer function:

# code

And now we can view the zoom-able and clickable TB graph.

If you haven't run the code, an already generated graph is [here](./trackable.pdf).

# code

This concludes our blog. For using the new GPU-related functionality, please click on our next blog.

** Many Smaller GPUs: Elegant In-Model Distribution

- From physical GPUs to custom configurable, virtual GPUs
- Stacks of Keras layers laid over parametric sequences of GPUs
- Instant, predictable and massive GPU computations/interactions
- Clean, clear model "pipelines" visualized and verified 

GPUs (and TPUs) are no doubt one of our most critical resources when running neural networks.

GPUs have strict capacities and limits as physical resources. When using servers with many smaller GPUs, we often ran into the inherent physical limitations of our equipment.

Laying out a possibly large model across many smaller GPUs has thus become a requirement for us. This blog presents a few basic steps in that direction.

The outlined model can also be used to effectively test more complex and custom GPU allocation strategies.

Our objective here is to arrive at training a model representable by the graph.

Just as before, we need to prep our environment to run any meaningful code:

# code

we also define a few convenient aliases

# code

For any effective and generalizable allocation strategy, we need to be able to reason about our resources uniformly.

We start with the new TF functionality of partitioning our physical GPUs into custom-sized, and thus easily "normalizable", virtual GPUs.

The components, or layers of our models, can then expect the ids of the properly sized, or allocated, virtual GPUs.

Given the parameter-driven "resource" requirements of our layers, we can also develop heuristics for partitioning and allocating the physical devices before starting a training session. Such heuristics are beyond the scope of this blog.

# code

let's turn off "soft" allocation for now

# code

The model we develop here builds on a configurable "stack" of identical layers.

A most basic, custom `dense` layer class is all we need as the stack's repeated component.

We aim to "lay" this stack on its side, and onto our virtual GPUs, as a functional, forward-backward propagating pipeline that could now fit in our combined GPU-space.

Each layer of the stack would, therefore, use a predetermined, or heuristically pre-calculated, virtual GPU `idx`:

# code

A basic `sequential` Keras model will suffice as the container of our stack.

Once our input, as well as the output, is shaped, we simply chain our chosen number of layers together, in the middle of our basic `sequential` model.

The Keras model's `summary` method is handy to confirm our model is laid out just as intended:

# code

Before we can run our model, we need to establish our parameters, the various dimensions and other attributes we want to use to shape the training.

A simple Python `dict` works best to keep things organized, unique and also sorted:

# code

The drawback of string keyed `dict`s is just that, the strings can have typos in them and hundreds of potentially misnamed parameters, later on, will certainly cause unnecessary confusion.

Python's automatically verified native `attribute`s come to the rescue once again.

Here is a simple, straightforward and functional `Params` class:

# code

Let's create our `Params` instance and a truly handy training data set (with testing and verification all built-in) in just one line of code:

# code

Finally, we are ready to compile our model. And, just as expected, the `summary` of the model shows that it has over 10 million weights.

The initial values of the weights are randomly picked. Through training, we bring these arbitrary values "inline" through millions of multiplications and additions executed by our many virtual GPUs, only to verify that our input `ones` are, in fact, just a series of `1`s:

# code

Training the model gives us the familiar Keras output, showing a nice convergence of a trivial problem across easily configurable GPUs:

# code

And now let's fire up TensorBoard and visually confirm that our stack of "dense" layers is connected just as expected.

If you haven't run the code, an already generated graph is [here](./gpus.pdf).

# code

This concludes our blog, please see how to use the new dataset functionality by clicking on the next blog.

** Dataset: The Tensor "Highway" On-Ramp

- Complex input data pipelines from simple, reusable pieces
- Starting from a "source", pipelines transform data streams
- New features allow splitting the streams into named "filaments"
- Performance and throughput is increased through file sharding 

Machine learning is about lots and lots of data. Organizing the input data is an error-prone, arduous task. 

TensorFlow `datasets` were designed to build complex input data pipelines from simple, reusable pieces with the clear objective of normalizing that process.

This blog shows off some of the useful features of this new approach to "feed the beast".

Before we can run any meaningful code, we first need to prep our environment:

# code

For convenience, and brevity, let's create some aliases as well:

# code

While computers were made to add numbers together, they quickly run into insurmountable obstacles if these numbers are presented as simple textual sequences of digits.

We aim to finally "teach" our computer to correctly add and multiply, just as we learned in elementary school. And we start with a simple yet fascinating example, inspired by https://arxiv.org/pdf/1812.02825.pdf.

Our input data consists of `num_samples` (perhaps easily millions) of `"x=-12,y=24:y+x:12"`-like strings, or lines, of texts. These visibly consist of `defs`, `op` and `res` fields (separated by `:`).

Our variables are: `x` and `y`, our "operations" are: `=`, `+`, `-` and `*`, and our variables can be assigned values from: `[-max_val, max_val]`.

The rest of the blogs in this group will continue to build on the below presented results:

# code

We also intend to make our input data pipeline parametric.

However, the obvious simple and intuitive Python `dict` structures, with literal string keys, are error-prone exactly because of unchecked literals.

A few lines of code gives as the `Params` class that leverages the native Python attribute mechanism to validate the names of all our params:

# code

Let's now randomly generate our data, fittingly as a Python generator, and based on a given `Params` instance. For this we define:

# code

With our generator defined, it takes just a line of code to create millions of correct "exercises" or samples for our training sessions:

# code

The `tf.data.Dataset` class is the main abstraction for our sequence of elements.

Each element of a dataset is one or more Tensors containing the fields, or `features`, of our `sample` "lines" of elementary math exercises.

Using our "in-memory" generator, we can directly create a TF dataset as follows:

# code

And here are the first 2 samples of the now tensor-based sequence:

# code

An input data pipeline starts with a "source" dataset, perhaps just as simple as the above.

This "source" can also be a `range`, `from_tensor_slices`, `from_tensors` and even a `TextLineDataset` (see the TF docs).

# code

All datasets can then be consumed one-by-one as iterables or as aggregatables (e.g. using reduce ops) collections.

Datasets also allow chaining of handy "transformations" to themselves. Some of the canned operations are the intuitive: *cache, concatenate, enumerate, reduce, repeat, shuffle, skip, take, zip*.

An example of 2 samples of a new dataset, concatenated with all 4 samples of the previous, gen-based, dataset and also "enumerated" on-the-fly is as follows:

# code

We can also filter our to be "pipeline" at any stage, with the objective of perhaps dropping unfit samples:

# code

More importantly, we can split the pipeline into named "filaments" of data.

This new feature proves to be extremely useful, allowing us to standardize and unify all our data sources with configurable, on-the-fly channeling of features aggregated therein:

# code

Another example of a "pipeline component" is an in-line Python `dict`-based tokenizer:

# code

Datasets can be potentially very large, fitting only on disk and in many files.

As transparent data-pipeline performance is key for training throughput, datasets can also be efficiently encoded into binary sequences stored in `sharded` files.

The following will convert our samples into such binary "records":

# code

And we can "dump" our tokenized, ready-to-consume samples into shards of files stored in a directory.

Once these prepared samples are stored, we can "stream" them straight into our models without any more prep (see subsequent blogs):

# code

For streaming, or loading the "records" back, we need to create templates used in interpreting the stored binary data.

With the templates defined, loading them back in, straight into our datasets, can be just as follows.

Note that the names of the shard files are conveniently returned by our "dump" function:

# code

Before we actually start using the loaded data in our models, let's "adapt" the pipeline to supply dense tensors instead of the originally configured sparse ones.

Also, since we haven't batched anything yet, we set `dim_batch` to `None`:

# code

The listing above reveals that we merged 3 sharded files, worth 4 samples each, into the 12 printed samples. We only printed the number of features for each sample, for brevity.

**Please also note** how the above in-line adapter converted our named features into unnamed, positional, i.e. in-a-list features. This was necessary as the Keras `Input` doesn't recognize named input tensors yet.

If we turn on batching in our dataset, the same code will now return the following:

# code

As preparation for the subsequent blogs, let's generate a more substantial data source with 10 shards of 1,000 samples each:

# code

This concludes our blog, please see how easy masking our uneven sample "lines" can be by clicking on the next blog.

** Unified Adaptable Masking That Follows The Flow

- Padding uneven input data can pollute our calculations
- It often seems best to cleanly "mask-out" padded values
- Keras' mechanism allows for on-demand custom maskings
- Without cluttering the flow, masking becomes transparent

A significant difference between image vs. text processing in machine learning is even vs. uneven input sequence length. Padding uneven textual input to a uniform length is an obvious, natural solution.

Indiscriminate padding can, however, pollute our calculations and introduce unwanted biases. Sometimes it is best to cleanly “mask-out” the padded input with carefully chosen, bias minimizing values.

Repeated, explicit and contextual masking calculations become necessary as a result. Historically such code has been cluttering the otherwise clean "flow of data". Keras’ transparent masking mechanism allows for on-demand custom maskings.

Our objective here is to arrive at a model representable by the [graph](./masking.pdf).

Just as before, we need to prep our environment to run any meaningful code:

# code

Loading our already created meta data from the sources gives us:

# code

To "adapt" our existing datasets, we recast our parsed streams and start using the new `RaggedTensor`s instead of the default sparse ones.

We also combine existing `feature`s into new ones by inserting separator tokens between the concatenated pieces.
 
Before handing the prepared streams of data to Keras, we still need to convert them to dense tensors. Most importantly, we pad the tensors to `len_max_input`, with generic zeros, for uniformity.

# code

A newly created function will return the paths to our existing file shards.

And now we are ready to create our datasets, custom-adapted to our problem at hand:

# code

Next, we need to tell our custom Keras layers to support masking. Let's do it once for all of them in our own `Layer` base class. We simply inherit from it for all other layers.

Our first layer, the one receiving the to-be-masked input and needing to specifically calculate the versatile `bool` masking tensor, has to override the `compute_mask` method.

We could also transfer the mask calculation to another layer that would do it as an efficient side-effect of its own tasks. In that case we would use the 2 commented out lines:

# code

In order to turn our impossibly "tight" `int32` tokens into something more useful for machine learning, we need to `Embed` them into a much higher dimensional "space".

Our embedding layer, however, is as simple as it gets: it first creates the embedding table and then does the actual lookup using the input tokens.

Once the embedded values are determined, we apply our straightforward `bool` masking cleanly, always resetting the masked-out, high dimensional values to `0` regardless of any "learned" adjustments.

During layer processing, Keras knows that we want to use the transparently hidden mask tensor from our included `mask=None` keyword argument in the `call` method's signature.

For `autograph`'s sake we need to also explicitly check that the optional `mask` argument is `not None`; a simple intuitive `if mask:` would only trigger "trace execution" instead of "graph execution" in our later blogs.

# code

Our self-attention layer, fittingly called `Reflect`, does the absolute minimum required steps to implement the "attention" mechanism of the `transformer` architecture. An excellent, creative explanation of how it works is at http://jalammar.github.io/illustrated-transformer/.

The masking tensor is being automatically supplied to the call by Keras. Once again, we only need to state our intention to mask by adding the `mask=None` keyword argument.

The actual masking calculation, based on our previously created `bool` tensor and specific for this layer only, is outright trivial. It simply replaces the to-be-masked values with large negatives:

# code

We are now ready to create and compile our Keras `functional` model.

As the objective of this blog is to showcase masking, all the other necessary "plumbing" layers are the canned Keras variety ones.

# code

The count of our parameters have slightly increased, otherwise they are the same as before. Please see the previous blog for the justification of the `Params` class and the overall scheme.

# code

Once we instantiate our parameters and our dataset, and using the already compiled model, we are ready to start a training session conveniently implemented by the Keras `fit` method.

Our aim is to use as much of the versatility, functionality and error checking that Keras provides, so using the model's `fit` method is all we need for now:

# code

With our TensorBoard `callback` in place, the model's `fit` method will generate the standard summaries that TensorBoard can conveniently visualize.

If you haven't run the below code, an already generated graph is [here](./masking.pdf).

# code

This concludes our blog, please see how to use the new `RaggedTensors` instead of masking by clicking on the next blog.

** Ragged Tensors Especially For Text Processing

- New ragged tensors expand existing composite tensors
- They can potentially solve data masking more efficiently
- Content and shape can be separated for ops efficiency
- Shapes are seamlessly re-applied once ops finish executing 

`RaggedTensor`s are a newly added feature in TF. They intend to cleanly and efficiently solve the previously mentioned "uneven sequence-length" problem.

While easily convertible, they are different from the more general `SparseTensor`s, as they only allow "ragged edges".

From an implementation point of view, `RaggedTensors` are efficiently represented as `composite tensor`s consisting of 1) a packed sequence of values and 2) a list of indices (effectively "row lengths").

These new composite tensors are purpose-fitted to our sample text processing problem.

One significant advantage of their specific design is the fluid nature of their "duality". On one hand, they can be viewed just as a simple vector of values, for efficient graph ops. On the other hand, they can be used as handy "masks", to selectively extract just the right values from dense tensors.

To demonstrate their use, we set our objective to arrive at a model representable by the [graph](./ragged.pdf).

Just as before, we need to prep our environment to run any meaningful code:

# code

Loading our already created meta data from the sources gives us:

# code

Our previously introduced `adapter` to our various datasets, themselves loadable from our stored samples, is adjusted slightly: we don't immediately convert the created ragged tensors to dense tensors anymore.

While Keras has the intention of supporting ragged input tensors (the `ragged=True` optional keyword argument is already available), passing in our `composite tensors` doesn't seem to work just yet. To work around this problem, we split our ragged tensors into its components, pass the components in and then reassemble them, once inside the model.

# code

With the adapter configured, our dataset streaming function is simple and looks as expected:

# code

Just as in our previous blog, our elementary math training problem calls for first embedding the passed-in tokens into more spacious hidden dimensions.

Hence our already defined `Embed` class only needs to be adjusted to work with ragged tensor arguments. Specifically, after reassembling our `RaggedTensor` inputs from its passed-in components, we simply apply our trusty `embedding_lookup` to all the flattened or "bunched-up" tokens:

# code

Our `Reflect` layer will need slightly more changes.

As the `flat_values` of our ragged inputs loose their batch dimensions, the matrix multiplications become simpler (expressed here through the favorite `einsum`, see [here](https://rockt.github.io/2018/04/30/einsum)).

Since the `attention` mechanism's `q`, `k` and `v` components are element-wise tied to their inputs, the new "raggedness" of the inputs doesn't change their scope. This means that we only need to change the content of our `RaggedTensor`s, the "row_lengths" stay the same as implemented by the `with_values` method.

When we switch over to cross-products, for scoring our calculated attention coefficients, we need to use dense tensors once again. But the actual result of the layer is a `RaggedTensor`.

Since its "raggedness" is the same as the layer's input's raggedness, we can conveniently recreate the same shaped `RaggedTensor` from the respective values of the just calculated dense tensor by using the original ragged input's `row_lengths` method. Very convenient indeed:

# code

We need to implement similar changes in our `Expand` layer.

"Inflating" our hidden dimensions, for the intrinsic learning purposes, requires a fixed width, hence we immediately convert to a larger dense tensor. However, as we are done with our "ragged" token calculations, we can simply pad the input to the layer to our expected `len_max_input`:

# code

We are ready now to define our model.

We have the two inputs, the two components of our input `RaggedTensor`. We also use our new `Embed`, `Reflect` and `Expand` layers adjusted to work with our sudden "raggedness". The rest of the model is simply carried over from the previous blog:

# code

Our parameters are also unchanged:

# code

By firing up our training session, we can confirm the model's layers and connections. Also, the listing of a short session follows.

We can easily adjust the parameters to tailor the length of the sessions to our objectives. However, at this point the results are still largely meaningless and extending the trainings is not yet warranted.

# code

With our TensorBoard `callback` in place, the model's `fit` method will generate the standard summaries that TB can conveniently visualize.

If you haven't run the code, an already generated graph is [here](./ragged.pdf).

# code

We can also switch over to the new `eager` execution mode. This is particularly convenient for experimentation, as all ops are immediately executed:

# code

And here is a much shortened `eager` session:

# code

This concludes our blog, please see how to avoid "layer-proliferation" complexity by clicking on the next blog.

** Unnecessary Complexity Through Layer Proliferation

- With complex requirements, Keras layers can seem "heavy" 
- A first take on `Transformer` mixes `layers` and `modules`
- Validated `functional` layers interconnect modules with bare ops
- We continue to expand on this "blended approach" of modeling

In this blog, we continue to elaborate on our loosely `transformer`-based approach to training our computer to "understand" elementary symbolic arithmetic. Just as previously mentioned, a quick and fun intro to the venerable transformer is [here](http://jalammar.github.io/illustrated-transformer/).

Our objective is to expand our layers' repertoire to include the `encoder` and the `decoder` stacks, as well as to ultimately arrive at a model representable by the [graph](./layers.pdf).

We need to prep our environment to run any meaningful code:

# code

Before we start to focus on our stacks, an important feature of encoding textual inputs needs to be considered. To aid in making sense of a text, we need to include not just the information carried by the tokens themselves but also their position in the input sequence.

Following the "positional encoding" approach from [here](https://github.com/tensorflow/examples/blob/master/community/en/position_encoding.ipynb), we can define our `pos_timing` function as follows.

The quick graphical plot helps us confirm the correctness of our code as the concatenated `sin` and `cos` timing signals give us finely graded and rich positional embeddings:

# code

Loading our already created meta data from the source files gives us:

# code

We continue with defining our own shared Keras "base" layer.

At this time, we only store a reference to our parameters instance in it, as all our layers will need to use this resource:

# code

The `Embed` layer is taken directly from our previous blog.

As we need to add the above mentioned positional "timing signals" to our embeddings, we first create just such a `constant` tensor.

Then, using the previously mentioned `RaggedTensor`-technique of extracting the ragged-shaped values from a dense tensor, we simply add the positional info to the already determined embedding:

# code

The next layers to write are the `Encode` and `Decode` stacks.

We implement them as simple lists of the respective `Encoder` and `Decoder` components. When calling the stacks, the code simply loops through the component lists and calls the components.

In order to "chain" the stacks, every component is given the output of the previous component as its input.

In the case of the `Decoder` components, and in addition to their regular inputs, we also supply the previously encoded output as their `ctx` argument:

# code

The mirror "image" of the `Embed` layer is our `Debed` layer.

While the embedding step maps `int` tokens to higher-dimensional, learned `float` values, the "debedding" step does the opposite. It takes the higher-dimensional values and maps them to learned `one-hot` vectors, corresponding to approximate output tokens.

As debedding is implemented using a `Dense` component, it also requires a fixed width. Just as in the previous blog, we simply pad our ragged tensors with `0`s to our `len_max_input` parameter, as our calculations are complete and the raggedness is not needed any longer:

# code

We have now completed the definition of our top layers as Keras layers, but we still need to define the inner components.

We could continue using the seemingly "heavy" Keras layers and nest them deeper. Instead, as presented in a previous blog, we switch over to using the much lighter-weight `Module` as the base class for our inner components.

Our `Encoder` thus becomes a simple module containing the self-attention followed by the feed-forward mechanisms. We fittingly call the inner modules `reflect` and `conclude`.

Our `Decoder` also adds the attention layer looking at the previously encoded "context". Hence, the module encapsulating this attention component is called `consider`:

# code

Our `Attention` component, again based on `Module`, is taken directly from the previous blog. As explained there, it relies on and takes advantage of the new `RaggedTensor`s:

# code

A new component is our `Conclusion` module. It implements the "feed-forward" functionality of the transformer.

In simple terms, it takes the attention-enhanced, higher-dimensional, element-wise mapping of the token sequence and it first `inflates` it to an even higher dimension with a non-linearity, or `activation`, at the end as its "concluding" step.

Then it `deflates` the activated mapping back to our hidden dimension, making it available for the next level in the stack.

The same `RaggedTensor` trick, as the one we used in the `Attention` module, applies at the end:

# code

Our last component is the `Dense` module.

It simply re-implements the Keras layer with the same name, yet with more focused, streamlined functionality and minimal configurability.

The interesting aspect of this module, just as our `Attention` module above, is that the necessarily created Keras weights are added using the enclosing Keras layer, however, topologically, they are directly listed as part of their respective modules:

# code

And now we are ready to define our model.

We have the two inputs, the two components of our input `RaggedTensor`.

We also use our new `Embed`, `Encode`, `Decode` and `Debed` Keras layers, with all the internal, light-weight modules hidden at this level.

The rest of the model is simply carried over from the previous blog:

# code

Our parameters need to be adjusted to provide parametric values for our stacks:

# code

By firing up our training session, we can confirm the model's layers and connections. The listing of a short session follows.

We can easily adjust the parameters to tailor the length of the sessions to our objectives. However, at this point the results are still largely meaningless and extending the trainings is not yet warranted.

# code

With our TensorBoard `callback` in place, the model's `fit` method will generate the standard summaries that TB can conveniently visualize.

If you haven't run the code below, an already generated graph is [here](./layers.pdf).

# code

We can also switch over to the new `eager` execution mode.

This is particularly convenient for experimentation, as all ops are immediately executed. Here is a much shortened `eager` session:

# code

This concludes our blog, please see how to further customize our model by clicking on the next blog.

** Custom Keras Layers Without The Drawbacks

- Standard layers seem either too complex or just plain trivial
- Large selection of options can obfuscate essential roles
- A `module` calling on needed bare ops directly is just a few lines
- Modules nested in custom layers benefit from the `functional` API

in this blog we continue to train our computer to "understand" elementary symbolic algebra
we slightly change our approach however
instead of having a fixed input/context for our encoder/decoder stacks, we follow the idea of "sliding contexts" from this [paper](https://arxiv.org/pdf/1901.02860.pdf)
in addition, we continue to architect our model with a mixture of "validated" Keras `layers` as well as light-weight `Modules` containing bare ops
our objective is to ultimately arrive to a model representable by the [graph](./custom.pdf)

just as before, we need to prep our environment in order to run any meaningful code

before we start, we need to increase our dataset slightly as the training steps are becoming more meaningful
calling the `dump_dset` function with a parameters object will update our stored binary file shards

for verification purposes, loading our already created meta data from the sources gives us

we also need to expand our previously used `formatter`
as we intend to concatenate subsequent inputs in our "sliding context", we need to end the result, `res`, feature of our samples with our `STP = "|"` token
please also note how we have started to use `tf.debugging.assert`s just to increase our confidence in the correctness of our data
later we will be able to switch these out with the familiar Python `asserts`

our `formatter` comes with an other significant adjustment
we intend to feed both our `encoder` and our `decoder` with inputs
namely, the encoder gets the full sample `defs` and `op`, while the decoder gets either a fully blank or a partially blanked `res`
so our dataset will supply an `enc`, a `dec` and a `tgt` (the full correct result of the math expression in the sample) tensors
the `rand_blank` function does the quick (inline) random blanking of the result to be fed into our `decoder`

in order for our dataset to be usable, we also need to update our `adapter`
we continue to still split our input ragged tensors into their components, and as we now have 3 ragged inputs (`enc`, `dec` and `tgt` as well, to give ourselves a choice of using custom `loss` and `metrics` implementations), the total number of input tensors to our model will thus be 6
the adapter needs to also supply our `tgt` dense tensor for the canned `loss` and `metrics` consumption

our new dataset creator function, `dset_for` is as follows
we added an optionally overridable `adapter` argument to be used later

as we now have 3 pairs of input tensors, that we need to convert back into `RaggedTensor`s, we quickly added a `ToRagged` convenience layer that can be seamlessly eliminated once the Keras `Input`s start properly supporting the `ragged=True` keyword argument

the `Frames` layer is the new significant addition
with every new input `xe` for the `encoder`, it first concatenates the `prev` stored context with `xe` into `ye`
and then it updates `prev`, to be used in the next cycle, with the concatenation of `ye` and the passed in result, `xt`
the computations are slightly complicated due to using the raggedness of the inputs to satisfy the continuous "sliding context" requirement
the layer also return the "row_lengths" for both `enc` and `dec` inputs
moreover, please note that the entire `Frames` layer works exclusively with tokens, as we don't want to keep already stale embedding calculations around in our "sliding context"

as our `Frames` layer returns fixed-width dense tensors, we can adjust our carried-over `Embed` layer to use the straight `embedding_lookup` optionally

we update the `Encode` and `Decode` layers with the addition of the `tf.function` decorators for the `call` methods

our `Debed` layer is also largely a carry-over, with the adjustment for the now fixed-width tensors

we update the `Encoder` and `Decoder` modules with the addition of the `tf.function` decorators for the `__call__` methods

the same applies to our new `Attention` module

the same applies to our new `Conclusion` module as well

to add the `tf.function` decorator to our `Dense` module, we simply inherit from the previous version

our model needs to be updated as well to use the newly defined components
another significant change is the addition of the "row_lengths" tensor  (directly from the ragged tensors) to all the input and output, now fixed-width dense tensors
once again, we were able to return to using dense tensors for our inputs, despite the "raggedness" of our samples, because we adopted the "sliding context" strategy, thus smoothly concatenating an entire "history" of inputs, into our "working set"

our parameters need to be expanded with the addition of the values for the now fixed widths of both our `encoder` and `decoder` 

by firing up our training session, we can confirm the model's layers and connections
the listing of a short session follows
we can easily adjust the parameters to tailor the length of the sessions to our objectives

with our TensorBoard `callback` in place, the model's `fit` method will generate the standard summaries that TB can conveniently visualize
if you haven't run the code below, an already generated graph is [here](./custom.pdf)

we can also switch over to the new `eager` execution mode
this is particularly convenient for experimentation, as all ops are immediately executed
and here is a much shortened `eager` session

this concludes our blog, please see how to use the `autograph` features with our model by clicking on the next blog

** Autograph: Intuitive Data-Driven Control At Last

- Ops solved complex calculations while failed at simple control
- Autograph transparently patches ops together for native control
- Control is intuitive at last from data-driven branching to searching
- On-the-fly "python ops" also provide insights into inner processes

continuing our blogs, we shift our focus to yet another new feature in TF, the `autograph` functionality
previously, and as far as intuitive expression of code was concerned, "graph ops" efficiently solved complex calculations while failed at simple, sequential control
by writing on-demand Python code now, `autograph` transparently patches all the necessary graph ops together and packages the result into a "python op"
while the generated new ops are potentially a lot faster than the code before them, in this blog we are more interested in the new expressive powers of the `autograph` package
specifically, we look at what becomes possible when decorating our functions with the new `tf.function` decorator, as doing this would by default invoke the `autograph` functionality
our objective is to ultimately arrive to a model of the generated new pops as represented by the [graph](./autograph.pdf)

just as before, we need to prep our environment in order to run any meaningful code

next, we borrow the `pos_timing` function from our previous blogs, and override it to return a constant "timing signal" tensor, depending on the `width` and `depth` arguments
as our first task is to implement a "python branch" in our new `Embed` op, we will be using two different "timing" tensors, one for the `encode` input and the other for the `decode` input

the `Embed` layer will thus create the two constant tensors
our model will call the shared `Embed` instance for both of our stacks
as we have decorated its `call` method with `tf.function`, we can use familiar and intuitive Python comparisons to branch on the value of tensors on-the-fly, during graph execution
clearly, our two stacks, while having the same `depth`s, have different `width`s
also the constant "timing" tensors have different `width`s as well
yet we are still able to pick-and-match the otherwise incompatible tensors and successfully add them together, all dependent on the `width` of our "current" input tensor

next we demonstrate how on-the-fly "python ops" can also provide insights into inner processes and data flows
we borrow our `Frames` layer from the previous blog and override its `call` method with a `tf.function` decorated new version that, besides calling on `super().call()`, also calls a new `print_row` Python function on every row in our batch
yes, we are calling a Python function and printing its results in a TF graph op while never leaving our intuitive and familiar Python environment! Isn't that great?
the `print_row` function itself is simple, it iterates through the tokens of the "row", it does a lookup of each in our `vocab` "table" for the actual character representing the token and then it joins all the characters and prints out the resulting string
and, if we scroll down to the listing of our training session, we can actually see the "sliding context" of our samples as they fly by during our training
needless to say, the listing confirms that our `Frames` layer does a good job concatenating the varied length sample inputs, the target results, as well as the necessary separators
as a result, a simple Python function usable during graph ops, provides us invaluable insights deep into our inner processes and data flow

our next new layer is the `Probe` layer, showcasing how control is intuitive at last from data-driven branching to searching
it is a temporary replacement for our previous `Debed` layer
the `Probe` layer implements an approximation of "Beam Search", see [paper](https://arxiv.org/pdf/1702.01806.pdf)
it effectively iterates through the hidden dimensions of the output, and based on parallel `topk` searches, comparing various choices for "debeding" the output, it settles on an "optimal" debedding and thus final token output for our `decoder`
the point of the `Probe` layer in the blog is to showcase data-driven iterations and parallel searches all implemented as "Python ops"
to be continued...

our model needs to be updated as well to use the newly defined components
other than that, we are ready to start training

by firing up our training session, we can confirm the model's layers and connections
the listing of a short session follows
we can easily adjust the parameters to tailor the length of the sessions to our objectives

with our TensorBoard `callback` in place, the model's `fit` method will generate the standard summaries that TB can conveniently visualize
if you haven't run the code below, an already generated graph is [here](./autograph.pdf)

this concludes our blog, please see how to use customize the losses and metrics driving the training by clicking on the next blog"

** Modular And Reusable Metrics All The Way

- Evaluating progress and results have always been too complicated
- Simple `loss` and aggregating `metric` APIs elegantly solve it now
- Customizing the "metering" protocol through subclassing is shown
- Blended, mixed metering strategies are now possible as well

as we have run various training sessions, and we have approached modeling itself from various angles, it is time for us to consider the piece of TF functionality that ties it all together
ultimately, the end goal of any modeling, and of the actual training with our models, is to arrive to simply quantifiable "measures", the `losses`, that we can then use in our repeated iterations of tuning the weights of the model
a `loss` is defined as some sort of difference, or "distance", between the results of our model's calculations and the given targets
specifically, we have been using `crossentropy`, (see a fun explanation [here](https://colah.github.io/posts/2015-09-Visual-Information/)) as that "distance"

just as before, we need to prep our environment in order to run any meaningful code

in order to be able to experiment with multiple `loss` and `metrics` settings, we duplicate our `tgt` tensors in our newly defined `adapter` function for our `dataset`

we also adjust our `ToRagged` layer
instead of leaving the `tf.function` decorator generic, which is allowing multiple version of the op to be generated based on the actual shapes of the input tensors
we restrict the generated op to only one version: the one taking any size 1D triple input pairs

and now we are ready to tackle replacement `loss` and `metric` classes
the Keras `losses.Loss` base class, that all the various other "losses" are derived from, has a `call` method with the above mentioned two arguments: the target tensor and the model's output tensor
our replacement implementation of the method skips the various checks and validations from the canned version and simply flattens the two known tensors followed by calling the efficient graph op implementation of crossentropy

our `Metric` class is even simpler, it adds the aggregating `total` and `count` variables and then delegates to calling our `xent` function (the same that our matching `Loss` uses)

our model needs to be updated to use the newly defined components, including our new `Loss` and `Metric`
as we include both the `Debed` and the `Probe` layers from our previous blogs, and they show up as a pair of output tensors respectively identifiable by their names, we can assign different losses and metrics to each
we chose to use the same `loss` and `metric` for both
Keras obviously will sum both losses and metrics to calculate the end result
nevertheless, since we have a pair of outputs, we also had to double the targets that the `loss` and `metric` would use

we also need to update our parameters with instances of our specific `Loss` and `Metric` instances we want Keras to call on

and now we are ready to start our training session
we can confirm the model's layers and connections
we can easily adjust the parameters to tailor the length of the sessions to our objectives

with our TensorBoard `callback` in place, the model's `fit` method will generate the standard summaries that TB can conveniently visualize
if you haven't run the code below, an already generated graph is [here](./metrics.pdf)

this concludes our blog, please see how to use Keras callbacks by clicking on the next blog"

** Keras Callbacks: Extending Their Scope And Usage

- Callbacks provide a framework for non-model specific event handling
- A flexible and uniform mechanism helps with automating
- Hyper-parameter tuning can also be aided by custom callbacks

this blog, as a transitioning piece between our to groups of blogs, is still work in progress
it concerns the various `callbacks` that we can register during training sessions
as automating our sessions is an important objective of ours, specifically to enable us to finetune our training `hyper-parameters`, we will be adding to this blog as the rest of the next group's blogs materialize

just as before, we need to prep our environment in order to run any meaningful code

and now we are ready to define our model
as this blog focuses on the actual training process, our model can be reused directly from a previous blog

once the model is defined, we now adjust our main calling function
at this point we define our `callbacks` that should be kept "in loop" during our training session
to be expanded...

we also need to update our parameters as they relate to our "callback objectives"
to be expanded...

and now we are ready to start our training session
we can confirm the model's layers and connections
we can easily adjust the parameters to tailor the length of the sessions to our objectives

to be expanded...


* Modeling Ideological Judicial Activism

** Introduction

We have outlined our overall objective and also have considered just the right tools to use to achieve it. In this second group of blogs, we set out to introduce the conceptual framework for our efforts.

We present a high-level, yet still easily simulatable view of our problem domain. We also define key abstractions to provide an unambiguous foundation for our subsequent work. And we clarify mechanism to numerically analyze, or just to simply measure, progress and results in a reproducible fashion. In the end, we also draw conclusions and offer usable "packaged" solutions.

Most importantly, we introduce a flexible, scalable and easily testable "proxy"-model that we can use to drive our deep-learning development. Our problem domain is clearly nebulous. Without firm and trustworthy guidance, we could easily lose direction.

As we are attempting to teach our computer to "understand" first, we reach for the ultimate, and undoubtedly universal, symbolic language: mathematics. To this effect, we have already introduced the problem of training elementary arithmetic in a previous [blog]().

With these blogs, we greatly expand on that first, exploratory attempt. There are numerous recent [results]() in NLP (natural language processing in AI) that approach or even surpass measured levels of human comprehension. We first provide a framework of modules that reproduce the ideas, schemes, and results presented in the latest published research.

As the symbolism of our "proxy" model is universally understood, meaning that it is fully predictable, synthesizing a virtually infinite and arbitrarily precise training sample base is within our reach. With purpose-built training data sets, we then build on the published state-of-the-art results, measurably fine-tuning them.

** Reductio Ad Absurdum - A Judicial Simulation

- Claims, proofs and realities
- "Conflicts are opportunities"
- Metrics: coherence, fragmentation
- Judgments: from certainty through ambiguity to absurdity

> "Reductio ad absurdum... is a form of argument that attempts to either disprove a statement by showing it inevitably leads to a ridiculous, absurd, or impractical conclusion, or to prove one by showing that if it were not true, the result would be absurd or impossible." - Wikipedia.

The **qnarre** narrative analyzing software operates on flat text statements represented by lists of sentences. The input **evidence** of a qnarre session is the list of all statements to be considered.

These statements are further grouped into an ordered list of **docs** of pages and paragraphs. The docs are persisted in varied formats in a hierarchical and rooted directory structure.

When a statement is assigned a **credibility** in qnarre, it becomes a **claim**. Credibility is an ordering of all claims defined to intuitively reflect that, for example, a police report or an allegation made during a trial in Court can be trusted more than a casual verbal opinion overheard on the street. 

All docs in qnarre belong to a **genre** (e.g. letter, motion, affidavit, judgment, etc.) that implicitly weighs all contained claims of the doc with an inherent, default credibility.

Claims can also be assigned incidental **weights** that fine-tune their individual credibilities. To model a doc of a specific genre, and containing 100 random claims, we can run the Python code presented below.

Before any of our simulations can be tried, or repeated with changed parameters, our environment needs to be initialized:

# code

Also, let's create 5 genres represented as their credibilities

# code

We define a function to conveniently create a new doc:

# code

Let's plot this, the chart will be randomly different with every run 

# code

The code above, and below, relies on randomly synthesizing varied data, or "sampling" from already created lists of values. These processes are defined in terms of their parameters.

All our simulations are thus driven by our input parameters and/or weights. Parameters and weights are real numbers, or Python *floats*. Some are from the interval [0,1] and can thus be directly used as *prior* probabilities.

Such parameters are:
- the number of docs in an input evidence is reflected by its **breadth**
- the number of claims in any specific doc is influenced by its **depth**.

To model an evidence of random docs with those parameters, we can run:

# code

Let's plot this

# code

The chosen simple probability distributions for the samples are noted through the choice of functions used. Numpy documentation provides further details.

More sophisticated, *generic* and even *conjugate* probability distributions can be easily plugged in to properly reflect inherent covariance and contravariance present in the data.

The credibility of a claim can be further enhanced by citing an *authority*. Such authority "witnessing" a claim will turn the claim into a **proof**. The *weight* of a proof derived from the authority is the enhancing factor of the underlying claim.

The percentage of proofs in an evidence is its **proven** parameter. To model an evidence witnessed, and thus proven, by authorities, we can run:

# code

Let's plot this

# code

Claims can be further categorized through *topics*. Grouping together varying topical claims and related proofs improves the understanding of the overall context in an evidence.

**Realities** are such contextual claims encapsulating the inherent, or readily and verifiably inferenceable, "common sense" credibilities.

The percentage of realities of all claims in an evidence is generated from its **contextual** parameter.

A reality, through the thus logically concluded credibility measure called its **coherence**, adds to the overall **certainty** of a simulation. We represent this *certainty* with a natural value of `1.0` and as an obvious upper bound of our charts and simulated "worlds".

Assuming that normal and balanced **ambiguity** rules before an evidence is ever considered, we can model how the realities of an evidence drive the overall understanding from *ambiguity* to *certainty* as follows.

Note that *ambiguity* has become our starting point, the "origin" and baseline with a natural value of `0.0` across the charts:

# code

Let's plot this

# code

And now our bounds for the world of trials:

# code

"*Conflict is opportunity*": good attorneys find intrinsic contradictions and conflicts in lawsuits and creatively expose the consequences, thus elevating or plausibly projecting neutral *ambiguity* to *certainty*. Judgments are then reproducibly made without further consequences and attorneys reap the rewards.

Without such conflicts, or the ability to find them, attorneys starve. Less capable yet "ambitious" or *malicious* attorneys professionally (i.e. "credibly") create, or plainly *fabricate*, artificial conflicts.

Such artificial **conflicts** are thus the fabricated claims that knowingly and purposefully hook into and then graft onto specific perceived realities of an evidence.

The objective of a \\[fabricated\\] *conflict* is to sow fear, uncertainty and doubt. A conflict, through its intended "credibility", defined hereon as its **fragmentation** measure, adds to the overall **absurdity**, or the level of confusion in the evidence and all its simulations.

So called "high-conflict" attorneys and professionals keenly understand the lucrative potential in this ruthless scheme and advertise their services as "aggressive", simply meaning maliciously *predatorial*, as shown in these simulations.

A conflict's *fragmentation* is thus expressed by, and is proportional to:
- its inherent *weight* measure (e.g. the modelled types of deception, fraud, extortion, etc.)
- the strength, the *coherence*, of its targeted reality (the more absurd something is the more confusion it creates when forcibly taken seriously).

Furthermore, just as a reality is enhanced by numerically more topical yet still semantically broad claims, a conflict is also emphasized by necessarily focused and narrow, almost literal, **repeats** along the famously quoted lines of the ruthless monster:  

> Repeat a lie often enough and it becomes the truth” - Nazi Joseph Goebbels

The percentage of conflicts of all claims in an evidence is generated from its malicious or **malignant** characteristic/parameter. We can model how the conflicts of an evidence fragment the overall reality of a simulation from *ambiguity* to *absurdity* as follows:

# code

Let's plot this

# code

Note that *absurdity* is now our lower bound in our charts, and simulations, and it is assigned an artificial value of `-2.0`. The value was chosen to reflect the significant antisymmetry between the necessarily coherent reality and the realm of widly fragmented, confused and outright dellusional "dreams have no limits" absurdity.

As opportunities dwindle in the realm of reality, creatively unbounded,  yet also morally unrestricted, select skilled professionals aim to "legally" profit from the unchartered, and truly vast, "Wild West" of absurdity.

**These simulations and software directly target such professionals, with the stated objective of systematically and sustainably profiting from their current and especially past exploiting escapades into the "Land Absurdity".**

Now that some of the used concepts have been defined, we can plot our target domain and its bounds as follows:

# code

Let's plot this

# code

**Judgments** are claims meant to forcefully solve conflicts. If the conflicts are inherent, or simply tractable, judgments restore and reinforce reality thus leading to an obviously sustainable, clear and fair *certainty*.

In a biased, or *prejudiced* simulation, reflected by the evidence's **prejudiced** parameter, the selected conflicts a judgement builds on greatly influence the credibility and thus the soundness of its own conjecture claim.

Judgments that are not sound (i.e. not coherent with reality) cause confusion and possibly destabilizing, long-term upheaval. A judgment's **turmoil** measure is thus expressed by, and is proportional to:

- its inherent *weight* measure (e.g. the modelled types of confusion, bias, fabrication, etc.)
- the actual influence, the sum of the *fragmentations* of all its referenced conflicts (inherent, tractable conflicts are not modelled as they are factored into the coherence of realities).

The percentage of judgments of all claims in an evidence is generated from its *breadth* characteristic/parameter. The *weights* of the judgments are proportional to the *prejudice* parameter of the evidence.

We can model how the judgments of an evidence cause consequential *turmoil* and drive a simulation from *ambiguity* to *absurdity* through confusion as follows:

# code

Let's plot this

# code

This concludes our blog. For more on modeling these concepts in detail, please click on our next blog.

** A Conceptual Model Of An "Emotional" Domain

- General underlying concepts
- Claims, topics and narratives revisited
- Broad realities vs. narrow conflicts
- From patterns of judgments to activism

We are only concerned with textual data stored electronically. A `source` is thus our generic unit of representation throughout the problem domain.

The `evidence` is the exhaustive collection of all the `doc`s we need to consider, organized hierarchically as individual `source`s.

Ultimately, it all comes down to working with text fragments, or `claims`, with their various interconnected and even overlapping properties and attributes. We formalize these and define:

| Term         | Definition                             | Properties                               |
| ---          | ---                                    | ---                                      |
| **Source**   | digitized content stored in a file     | type (e.g. pdf, jpg, email, text)        |
| **Evidence** | a hierarchy of considered Sources      | root (directory)                         |
| **Doc**      | paginated flat textual Evidence        | name (date), genre, author, title, pages |
| **Genre**    | the "officialness" of a Doc            | name                                     |
| **Place**    | a specific location in a Doc           | doc, page, para(graph)                   |
| **Claim**    | a Placed relevant text fragment        | text, place                              |

The `author` of a `doc` of implicitly related set of `claim`s can be a party, a lawyer or a judge, for example. Accordingly, we define:

| Term          | Definition                            | Properties                           |
| ---           | ---                                   | ---                                  |
| **Author**    | an author of Docs of Claims           | name, title                          |
| **Agent**     | a to be believed professional         | kind (of profession)                 |
| **Authority** | a trusted Agent of an official agency | agency (institution or 'sworn self') |

A `claim` can be grouped into `topic`s and attached to `narrative`s. Such groupings and assignments are done based on the semantic meaning of the claim, as well as the context the claim belongs to.

| Term          | Definition                                    | Properties  |
| ---           | ---                                           | ---         |
| **Topic**     | a relevant/dominant subject matter of Claims  | name        |
| **Narrative** | a thematically focused "slice" through Claims | name, topic |

More importantly, `claim`s are further categorized as follows. The objective is to either compute a generalizing `credibility` for the claim or to derive other reproducible conjectures regarding the related claims. 

| Term           | Definition                                                | Properties       |
| ---            | ---                                                       | ---              |
| **Node**       | a generic grouping of Claim(s) along thematic dimensions  | topic, narrative |
| **Proof**      | a readily verifiable undisputed Claim from an Authority   | claim, authority |
| **Conjecture** | a logical inference from Proofs guided by thematic Claims | proofs, claims   |
| **Reality**    | a broad-based reinforcing Conjecture                      | coherence        |
| **Dissent**    | a narrow, fragmenting and thus weakening Conjecture       | fragment         |

A `dissent` is further broken down into self-explained types with increasing factors of their fragmenting effects. These are:

| Term                | Definition                                                       |
| ---                 | ---                                                              |
| **Misreading**      | stated seemingly unintentionally misinterpreted relevant claims  |
| **Fairness**        | neglected or refused to consider both claim and counterclaim     |
| **Negligence**      | reported relevant and damaging information in a careless manner  |
| **Proportionality** | neglected or refused to report in balanced/proportional manner   |
| **Contradiction**   | neglected or refused to state apparent inconsistency or conflict |
| **Isolation**       | neglected or refused to consider relevant and essential context  |
| **Omission**        | neglected or refused to report disclosed relevant information    |
| **Distortion**      | reported relevant information in a suggestive and biased manner  |

A special type of a claim is a `conflict`. Its purpose is to directly contradict a `reality` and thus to manipulate a subsequent `judgment`.

| Term         | Definition                                                      | Properties           |
| ---          | ---                                                             | ---                  |
| **Conflict** | a Claim intended to fabricate/escalate bases for Judgments      | claim, reality       |
| **Suborn**   | a false Claim caused by Agent as intentional perjury            | (agent's) agency     |
| **Repeat**   | variant of conflict inducing Claim to reinforce intended effect | claim, conflict      |
| **Judgment** | a thematic conjecture by Authority over inflated Conflicts      | conflicts, authority |
| **Activism** | a thematic pattern of conjectures by Authority                  | judgments, authority |

Revealing, and even fabricating, conflicts is the objective of lawsuits. We categorize conflicts along their increasing fragmenting effect on judgments: 

| Term         | Definition                                                       |
| ---          | ---                                                              |
| **Inherent** | emphasized inherent contradictions to confuse judgment           |
| **Conceal**  | intentionally concealed relevant truths to affect judgment       |
| **Deceive**  | intentionally emphasized relevant half-truths to affect judgment |
| **Fraud**    | stated intentionally falsified relevant and crucial information  |
| **Extort**   | stated relevant and threatening claims to force money or "fees"  |

The judgments of lawsuits represent the net effect of all the claimed conflicts. If a `judgment` relies predominantly on conflicts while overruling realities, it causes `turmoil`. The types of judgments we consider in increasing turmoil effect is as follows: 

| Term            | Definition                                                         |
| ---             | ---                                                                |
| **Validation**  | selection and judgment of conflicts refuting an inflated Conflict  |
| **Confusion**   | selection and judgment of conflicts leading to clear contradiction |
| **Bias**        | selection and judgment of conflicts satisfying a prior narrative   |
| **Disregard**   | avoidance of relevant conflicts while protecting a prior narrative |
| **Fabrication** | injection of disputable conjecture reinforcing a prior narrative   |

When considering multiple judgment claims, a pattern, a trend can possibly be established. During processing, when our calculations support such patterns, `activism`s emerge. We define the following categories in increasing effect on their `turmoil` factor:

| Term           | Definition |
| ---            | ---        |
| **Exclude**    | pattern of |
| **Insinuate**  | pattern of |
| **Polarize**   | pattern of |
| **Recast**     | pattern of |
| **Elevate**    | pattern of |
| **Victimize**  | pattern of |
| **Exploit**    | pattern of |
| **Perpetuate** | pattern of |

** The Predatory Profits Of "High-Conflict" Divorces

- In progress...
TODO: expand bullets

** A Psychological Object Model Of The ABA "Frequent Fliers"

- In progress...

** From Purposefully Fabricated Conflicts To Ideological Activism

- In progress...

** Representative Metrics Through Statistical Modeling

- In progress...

** Learn, Adapt And Protect Effectively From "Elite" Predators

- In progress...


* Court Contradictions Analytically Evaluated

** Introduction

In this third group of blogs, we finally turn our attention back to the concrete tasks we need to perform to accomplish our objectives. Reusing the generalizable mechanisms and results from the previous section, we outline our now textual input preparation steps. We also specify the format of our outputs, optimized on purpose for flexibility and versatility during subsequent processing.

The effective product of all the activities presented in this section is the "conflict graph", a condensed summary of the now "understood" meaning of our input texts. This graph is then interpreted and used to synthesize various metrics and statistics about the semantic context of our data. We describe the graph in more detail and supply a set of custom operators on it.

We also outline an introductory sampling of analytics. As the end-results are all reproducible, traceable and verifiable numeric quantities, standard data-mining and "big-data" practices can be applied. We end the blogs by presenting just such a "data-mined" report, based on actual filed documents and Court proceedings.

** Preparing and normalizing legal documents
** Tagging with **topics** and extracting **narratives**
** Standardized output and flexible reporting
** Interpreting and presenting inferred **conflict graphs**
** Irrefutable analytics to unmask ruthless "cover-ups"
** Trends, costs and **profits** while identifying motives
** "Based on a true story": a sample Qnarre report 


* Narratives For Real-Estate?

** A "for hire" study of scenarios and results
